on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  test-actions:
    runs-on: ubuntu-latest
    steps:
      - run:
        name: Docker build testing
        docker build -f docker/Dockerfile.testing -t bigomics/omicsplayground:testing .
